raw <- read.csv("../test_validateDup.csv")

occs <- formatDwc(user_data = raw)
occs <- formatOcc(occs)
occs <- formatLoc(occs)
occs <- formatTax(occs)
occs <- formatCoord(occs)
occs <- validateLoc(occs)
occs <- validateTax(occs)
occs <- validateCoord(occs)
occs <- validateDup(occs)
occs2 <- validateDup(occs, prop = 0.9)
occs3 <- validateDup(occs, prop = 0.25)
all.equal(occs3, occs2)
write.csv(occs, "tests/test_validateDup.csv")
