test_that("prepName works", {
  expect_equal(prepName("Alwyn H. Gentry"), "Gentry, A.H.")
  expect_equal(prepName("Alwyn H. Gentry", fix.names = FALSE), "Gentry, A.H.")
  expect_equal(prepName("Alwyn H. Gentry", format = "init_last"), "A.H. Gentry")
  expect_equal(prepName("Alwyn H. Gentry", get.initials = FALSE, format = "init_last"), "Alwyn H. Gentry")
  expect_equal(prepName("Alwyn H. GENTRY", pretty = FALSE), "GENTRY, A. H.")
  expect_equal(prepName("Karl Emrich & Balduino Rambo", sep.out = "&"),
               "Emrich, K.&Rambo, B.")
  expect_equal(prepName("R. Reitz; R.M. Klein"), "Reitz, R.|Klein, R.M.")
  expect_equal(prepName("Reitz, Raulino et R.M. Klein"), "Reitz, R.|Klein, R.M.")
  expect_equal(prepName("Carl F. P. von Martius; Augustin Saint-hilaire"),
    "Martius, C.F.P.|Saint-Hilaire, A.")
  expect_equal(
    prepName("Carl F. P. von Martius; Auguste de Saint-Hilaire", get.prep = F),
    "Martius, C.F.P.|Saint-Hilaire, A."
  )
  expect_equal(prepName("A. ducke; dárdano de Andrade-Lima"),
               "Ducke, A.|Andrade-Lima, D.")
  # Names with generational suffixes
  expect_equal(prepName("HF Leitão Filho; GJ Shepherd", special.char = TRUE),
    "Leitão Filho, H.F.|Shepherd, G.J.")
  # Names with titles
  expect_equal(prepName("Pe. Raulino Reitz"), "Reitz, R.")
  expect_equal(prepName("Prof. Hermogenes de Freitas Leitao Filho"),
               "Leitao Filho, H.F.")
  expect_equal(prepName("Sir G.T. Prance"), "Prance, S.G.T.")
  expect_equal(prepName("Sir G.T. Prance", treat.prep = "Sir"), "Prance, G.T.")
  expect_equal(prepName("Dra. Gloria Galeano"), "Galeano, G.")
  expect_equal(prepName("[D. Hugh-Jones]"), "[Hugh-Jones, D.]")
  expect_equal(prepName("L. McDade & J. O'Brien"), "McDade, L.|O'Brien, J.")
  # Other cases
  expect_equal(prepName("HF Leitão Filho; GJ Shepherd", output =  "aux"),
               "Shepherd, G.J.")
  expect_equal(prepName("HF Leitão Filho; GJ Shepherd; RR Rodrigues", output =  "aux"),
               "Shepherd, G.J.|Rodrigues, R.R.")

  expect_equal(prepName("(HF Leitão Filho)"),"(Leitao Filho, H.F.)")
  expect_equal(prepName("HF Leitão Filho (no. 100)"),"Leitao Filho, H.F.")

})

## All below should work
input <- c( "(HF Leitão Filho)",
            "[D. Hugh-Jones]",
            "AHG",
            "AL",
            "A. Alvarez, A. Zamora & V. Huaraca",
            "A. Alvarez; A. Zamora & V. Huaraca",
            "Alwyn",
            "alwyn",
            "ALWYN",
            "Azevedo, T.I.N.,Azevedo, SI",
            "Renato de la Barra",
            "Braak, Hans ter",
            "Braak, Hanster",
            "Hans ter Braak",
            "Hanster Braak",
            "ter Braak, Hans",
            "Neto, F.C.C.",
            "Alphonse Louis Pierre Pyrame de Candolle",
            "Costa, M. A., Ribeiro, J.",
            "Costa M. A., Ribeiro J., E. C. Pereira",
            "Costa, M. A., Ribeiro J., E. C. Pereira",
            "M. A. Costa, J. Ribeiro & E. C. Pereira",
            "M. A. Costa, J. Ribeiro, E. C. Pereira",
            "M. A. Costa, Ribeiro, J. O., E. C. Pereira",
            "M. A. Costa, Ribeiro, J., E. C. Pereira",
            "M. A. Costa, Ribeiro, J.O., E. C. Pereira",
            "M. A. Costa|J. Ribeiro|E. C. Pereira",
            "A. Ducke; Dárdano de Andrade-Lima",
            "A. ducke; dárdano de Andrade-Lima,",
            "Ducke, A.; Dárdano de Andrade-Lima",
            "Karl Emrich & Balduino Rambo",
            "J.E.Q. Faria Jr.",
            "Filho Neto, S.J.",
            "S.J. Filho Neto",
            "Dra. Gloria Galeano",
            "Gentry",
            "gentry",
            "GENTRY",
            "A. Gentry",
            "Al Gentry",
            "Gentry, A.",
            "A H Gentry",
            "a. h. gentry",
            "a. h. Gentry",
            "A. H. GENTRY",
            "A. H. Gentry",
            "a.h. gentry",
            "A.H.Gentry",
            "AH gentry",
            "Ah. Gentry",
            "Alwyn H. Gentry",
            "Alwyn Howard Gentry",
            "ALWYN HOWARD GENTRY",
            "GENTRY A.H.",
            "Gentry A.H.",
            "Gentry AH",
            "GENTRY, A H",
            "gentry, a. h.",
            "gentry, a.h.",
            "Gentry, AH",
            "Gentry, Alwyn Howard",
            "GENTRY, ALWYN HOWARD",
            "Alwyn H. Gentry|Elsa M. Zardini",
            "G. G. HATSCHBACH",
            "Gert G. Hatschbach",
            "Gert G. Hatschbach, et al.",
            "HATSCHBACH, G. G.",
            "HATSCHBACH, G.G.",
            "Augustin Saint Hilaire",
            "Jan van der Hoeven",
            "Hermogenes Leitao Filho",
            "Leitao Filho, H.",
            "H. F. Leitao filho",
            "H.F. Leitao Filho",
            "Hermogenes de Freitas Leitao Filho",
            "HF Leitão Filho (no. 100)",
            "Leitão F°, H.F.",
            "Leitao filho, H. de F.",
            "Leitao filho, H. F.",
            "Leitao Filho, H.F.",
            "Leitao Filho, HF",
            "Prof. Hermogenes de Freitas Leitao Filho,",
            "HF Leitão Filho; GJ Shepherd",
            "Leitão Filho, H.F.; Shepherd, G.J.",
            "Leitão Filho, H.F.;Shepherd, G.J.",
            "HF Leitão Filho; GJ Shepherd; RR Rodrigues",
            "John MacDonald",
            "Carl F. P. von Martius",
            "Carl Friedrich Philipp von Martius",
            "Carl F. P. von Martius; Augustin Saint-hilaire",
            "L. McDade",
            "L. McDade & J. O'Brien",
            "John Mc Donald",
            "John McDonald",
            "Mendonca Filho, C.V.; Neto, F.C.C.",
            "  'Pedro L.R.de Moraes (30/4/1998)'",
            "M. Nadruz; ,J.F. Baumgratz, M. Bovini, D.S.P. Silva",
            "Neto",
            "John O' Brien",
            "John O'Brien",
            "John O'Reilly",
            "Simon Jan van Ooststroom",
            "P Filho",
            "E. P. Filho",
            "Elton P. Filho",
            "Filho, Elton P.",
            "E L P Filho",
            "Filho, E L P",
            "Filho, E. L. P.",
            "Filho, E.L.P.",
            "E. Pereira Filho",
            "Elton Pereira Filho",
            "Filho, E. Pereira",
            "Filho, Elton Pereira",
            "E.L. Pereira Filho",
            "E. L. P. Filho",
            "Sir G.T. Prance",
            "J. F. Morales Quirós; Michael H. Grayum ; Maria M. Chavarría",
            "Pe. Raulino Reitz",
            "R. Reitz; R.M. Klein",
            "Raulino Reitz; R.M. Klein",
            "Reitz, Raulino et R.M. Klein",
            "Ribas, O.S.,Petean, M.P.,Labiak, P",
            "Cyl Sa",
            "Sa, Cyl",
            "Cyl Farney Catarino de Sa",
            "saint-hilaire",
            "A. Saint-Hilaire",
            "Auguste de Saint-Hilaire",
            "Auguste Saint-Hilaire",
            "Augustin Saint-hilaire",
            "Augustin Saint-Hilaire",
            "Saint-Hilaire A.",
            "Saint-Hilaire, Augustin",
            "Saint-Hilaire, augustin",
            "Cesar Sandro, Esteves, F",
            "da Silva",
            "Silva",
            "Silva, da",
            "Silva, D",
            "Silva, Da",
            "D. A. Silva",
            "D.A. Silva",
            "DA Silva",
            "Daniela A. Silva",
            "Silva, D A",
            "Silva, D. A.",
            "Silva, D.A.",
            "Silva, DA",
            "Silva, Daniela A.",
            "D A M Silva",
            "Silva, D A M",
            "Silva, J.M.,Barboza, E.,Silva, JM",
            "da Silva, M.",
            "Maria da Silva",
            "Silva, M. da",
            "da Silva, Maria A. Pereira",
            "Maria A. Pereira da Silva",
            "Maria A. Pereirada Silva",
            "Silva, Maria A. Pereira da",
            "Silva, Maria A. Pereira Da",
            "Silva, Maria A. Pereirada",
            "Souza 35",
            "HANS TER STEEGE",
            "TER STEEGE, HANS",
            "  'F. da S.N. Thomé'",
            "F.daS.N.Thomé",
            "Tiritan, O; Paiva, M")
expect <- c(  "(Leitao Filho, H.F.)",
              "[Hugh-Jones, D.]",
              "Ahg",
              "Al",
              "Alvarez, A.|Zamora, A.|Huaraca, V.",
              "Alvarez, A.|Zamora, A.|Huaraca, V.",
              rep("Alwyn", 3),
              "Azevedo, T.I.N.|Azevedo, S.I.",
              "Barra, R.",
              rep("Braak, H.", 5),
              "C. Neto, F.C.",
              "Candolle, A.L.P.P.",
              "Costa, M.A.|Ribeiro, J.",
              rep("Costa, M.A.|Ribeiro, J.|Pereira, E.C.", 4),
              "Costa, M.A.|Ribeiro, J.O.|Pereira, E.C.",
              "Costa, M.A.|Ribeiro, J.|Pereira, E.C.",
              "Costa, M.A.|Ribeiro, J.O.|Pereira, E.C.",
              "Costa, M.A.|Ribeiro, J.|Pereira, E.C.",
              rep("Ducke, A.|Andrade-Lima, D.", 3),
              "Emrich, K.|Rambo, B.",
              "Faria Junior, J.E.Q.",
              "Filho Neto, S.J.",
              "Filho Neto, S.J.",
              "Galeano, G.",
              rep("Gentry", 3),
              rep("Gentry, A.", 3),
              rep("Gentry, A.H.", 8),
              "Gentry, A.",
              rep("Gentry, A.H.", 12),
              "Gentry, A.H.|Zardini, E.M.",
              rep("Hatschbach, G.G.", 5),
              "Hilaire, A.S.",
              "Hoeven, J.",
              rep("Leitao Filho, H.", 2),
              rep("Leitao Filho, H.F.", 10),
              rep("Leitao Filho, H.F.|Shepherd, G.J.", 3),
              "Leitao Filho, H.F.|Shepherd, G.J.|Rodrigues, R.R.",
              "MacDonald, J.",
              "Martius, C.F.P.",
              "Martius, C.F.P.",
              "Martius, C.F.P.|Saint-Hilaire, A.",
              "McDade, L.",
              "McDade, L.|O'Brien, J.",
              "McDonald, J.",
              "McDonald, J.",
              "Mendonca Filho, C.V.|C. Neto, F.C.",
              "Moraes, P.L.R.",
              "Nadruz, M.|Baumgratz, J.F.|Bovini, M.|Silva, D.S.P.",
              "Neto",
              "O'Brien, J.",
              "O'Brien, J.",
              "O'Reilly, J.",
              "Ooststroom, S.J.",
              "P. Filho",
              rep("P. Filho, E.", 3),
              rep("P. Filho, E.L.", 4),
              rep("Pereira Filho, E.", 4),
              "Pereira Filho, E.L.",
              "P. Filho, E.L.",
              "Prance, S.G.T.",
              "Quiros, J.F.M.|Grayum, M.H.|Chavarria, M.M.",
              "Reitz, R.",
              rep("Reitz, R.|Klein, R.M.", 3),
              "Ribas, O.S.|Petean, M.P.|Labiak, P.",
              "Sa, C.",
              "Sa, C.",
              "Sa, C.F.C.",
              "Saint-Hilaire",
              rep("Saint-Hilaire, A.", 8),
              "Sandro, E.C.",
              rep("Silva", 3),
              "Silva, D.",
              "Silva",
              rep("Silva, D.A.", 9),
              "Silva, D.A.M.",
              "Silva, D.A.M.",
              "Silva, J.M.|Barboza, E.|Silva, J.M.",
              rep("Silva, M.",  3),
              rep("Silva, M.A.P.", 6),
              "Souza",
              "Steege, H.",
              "Steege, H.",
              "Thome, F.S.N.",
              "Thome, F.S.N.",
              "Tiritan, O.|Paiva, M."
              )

test_that("prepName works fully", {

  expect_error(prepName(NULL), NA_character_)

  expect_equal(prepName(""), NA_character_)
  expect_equal(prepName(" "), NA_character_)
  expect_equal(prepName(NA_character_), NA_character_)
  expect_equal(prepName("15/04/1985"), NA_character_)

  expect_equal(prepName(input), expect)

} )

## Not working yet (move up if any start working)
input1 <- c("E.,Aguilar, G.,Alvarez, D,Ramos A., CH",
            "  '( Karl) Emrich ;(Balduino ) Rambo'",
            "G., Alwyn",
            "SILVA, DA",
            "DA SILVA")
expect1 <- c("E.|Aguilar, G.|Alvarez, D.|Ramos A., C.H.",
             "Emrich, (K.)|Rambo, (B.)",
             "G., A.",
             "Silva, D.A.",
             "Silva, D.A."
)
test_that("prepName not works", {

  expect_error(expect_equal(prepName(input1), expect1))

} )
