utils::globalVariables(c(".",
                         "as col.OBS",
                         "col.OBS",
                         "comb.fields",
                         "dup.ind.test",
                         "ignore.miss",
                         "ignore.na",
                         "index.herbariorum.or.working.code",
                         "latamMap",
                         "loc.correct",
                         "NAME_0",
                         "noName",
                         "noNumb",
                         "noYear",
                         "occs",
                         "ordem.dados",
                         "pais_latam",
                         "pais_wo",
                         "tmp.ordem",
                         "worldMap")
)

